### ISSUE TITLE
Add Objects and Arrays to properties in Encoding attributes

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/vector-tiles#12]
@mapsam these docs are great! Thanks!

One question I've had a few times is how objects and arrays are handled when going from geojson to vector tiles. From my own experience I know we stringify these and treat them as strings in the vector tile. As that isn't the clearest process to end users, I think we should show an example of this [in the encoding example](https://www.mapbox.com/vector-tiles/specification/#encoding-attr).

I'm not 100% clear how these docs are being generated, but if you point me in the right direction I'd be happy to make the PR.

**Comment by mapsam** [comment]
This is something I've been thinking through as well @mcwhittemore. I'd love to see a super explicit example showing how [command integers](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#431-command-integers) and [parameter integers](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#432-parameter-integers) are calculated and encoded. I went down a big rabbit hole when researching bit shifting & and the binary math behind the geometry encoding, and didn't have time to emerge with a visual.

One thing to keep in mind, the "hover on the geojson and see it in the protobuf" example is already at the maximum usable height on the page, maybe we can create a second one specifically about geometry and put it in the [geometry encoding](https://www.mapbox.com/vector-tiles/specification/#encoding-geom) section?

All ideas are welcome!

> how these docs are being generated

Each section in the specification page is a `.md` post in `_posts/spec`. They have the HTML and JS directly in the file. https://raw.githubusercontent.com/mapbox/vector-tiles/mb-pages/_posts/spec/0001-01-06-encoding-attributes.md

**Comment by mcwhittemore** [comment]
Oh! @mapsam, I was thinking about objects and arrays as values in the properties object of GeoJSON, not the fun truncating stuff that happens in the geometry. Sorry if that wasn't clear.

**Comment by mapsam** [comment]
Ohhh doh I totally didn't grok that. I think that'd be a sweet thing to show. Might need some help from @flippmoke on this one.

@flippmoke what do `tags` look like when a feature has a property that is an array or object? 

```JSON
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "things": ["one", "two", 3],
    "stuff": { "waka": "flocka", "hello": "world" }
  }
}
```

**Comment by mcwhittemore** [comment]
I'm pretty sure the values are

* `"[\"one\",\"two\",3]"`
* `"{\"waka\":\"flocka\",\"hello\":\"world\"}"`

**Comment by mapsam** [comment]
@mcwhittemore been thinking about this and how to accurately highlight arrays & objects. Since the specification does not mention this (intentionally) that means it is up the encoder to decide (i.e. this is how Mapnik handles it). 

I don't want to make it seem like _stringifying_ SHOULD be done by including it in the example. I wonder if adding a section to the "what the spec doesn't cover?" would be helpful? Something like:

#### How to encode attributes that aren't strings or numbers

Attributes in geometric data, such as the `properties` object in GeoJSON can include more than just strings and numbers. They can be arrays or objects. The specification doesn't cover how to encode these values and is up to the encoder to decide. Tools like Mapnik will turn arrays and objects into strings, which requires the decoder to parse them accordingly. For example, if you had a GeoJSON property called `categories` and it was an array:

```
"categories": ["one", "two", "three"]
```

It would be converted into a string and stored in the protobuf like this:

```
keys: "categories"
values: {
  string_value: "[\"one\",\"two\",3]"
}
```

**Comment by mcwhittemore** [comment]
Hmmm... I'd be interested in understanding why this isn't covered by the spec. GeoJSON to VT seems like a pretty normal encoding process.

Having a section on what the spec doesn't cover seems like a good idea. I'm assuming what is covered in this section will be considered in future versions of the spec and that by putting examples of how to handle unspecified situations will give implementors a resource when considering their options for this kind of encoding.

**Comment by mapsam** [comment]
I think it is definitely worthy to include in the spec.  For now I'm going add a section to "what it doesn't cover". Probably worth re-opening https://github.com/mapbox/vector-tile-spec/issues/75 to talk about adding it to the spec.

**Comment by mapsam** [comment]
added in 49b3957f2b4af5ec2296a8f6b088635cf41cf8d7
